### PR TITLE
open bundle path using $TERM_PROGRAM

### PR DESCRIPTION
**Pull request by milligramme**
`% tmb cd PARTIAL_NAME` use Terminal.app by default.
But I want to use iTerm.app, using environment variable  $TERM_PROGRAM will solve this issue.

### CODE REVIEW

**Comment by elia** [comment]
Thanks!

**Comment by milligramme** [comment]
Thanks for merging.
By the way, it seems this gem did not update version and release to rubygems.org after  v0.1.2.
Is there release schedule?

**Comment by elia** [comment]
no, but I can release it right now 😄

**Comment by elia** [comment]
And [done!](https://rubygems.org/gems/tmbundle-manager/versions/0.1.3) 👍🏼

**Comment by milligramme** [comment]
thanks a lot!

**Pull request merged**
